[ui]
page_title = "ê³ ë ¹ì êµí†µì‚¬ê³  ì˜ˆì¸¡ ì„œë¹„ìŠ¤"
page_icon = "ğŸš—"  # ì›í•˜ëŠ” ì´ëª¨ì§€ ê°€ëŠ¥

[theme]
base="light"
primaryColor="#4B8BBE"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"